[manifest]
version = "1.0.0"
priority = 0

[[patches]]
[patches.pattern]
target = 'functions/common_events.lua'
pattern = '''        trigger = 'before',
        delay = delay,'''
position = 'at'
match_indent = true
times = 1
payload = '''
blocking = Balatest.current_test == nil,
-- blockable = Balatest.current_test == nil,
'''
